config/routes.rb
IncidentManagementFramework::Application.routes.draw do

  resources :executables do
		collection do
			get 'uploadExe'
			post 'uploadExe'
		end
	end

  resources :variables

  resources :incidents do
		resources :micro_incidents
	end

	root to: "incidents#index"

end

app/helpers/executables_helper.rb
module ExecutablesHelper
end

app/views/executables/edit.html.erb
<h1>Editing executable</h1>

<%= render 'form' %>

<%= link_to 'Show', @executable %> |
<%= link_to 'Back', executables_path %>

app/views/executables/index.html.erb
<h1>Listing executables</h1>

<table>
  <thead>
    <tr>
      <th>MD5</th>
      <th>SHA1</th>
      <th>SHA256</th>
      <th>AV detection</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @executables.each do |executable| %>
      <tr>
        <td><%= executable.md5 %></td>
        <td><%= executable.sha1 %></td>
        <td><%= executable.sha256 %></td>
        <td><%= executable.av_detection %></td>
        <td><%= link_to 'Show', executable %></td>
        <td><%= link_to 'Edit', edit_executable_path(executable) %></td>
        <td><%= link_to 'Destroy', executable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Executable', new_executable_path %>

app/views/executables/invalidFile.html.erb
<center><h1>Invalid file</h1></center>
...

app/views/executables/new.html.erb
<h1>New executable</h1>

<%= render 'form' %>

<%= link_to 'Back', executables_path %>

app/views/executables/uploadExe.html.erb
<br />
<h1>File Upload</h1>
<%= form_tag 'uploadExe', :multipart => true do %>
   <label for="file">Upload file</label> <%= file_field_tag "file" %>
   <%= submit_tag %>
<% end %>