config/routes.rb
IncidentManagementFramework::Application.routes.draw do

  resources :executables do
		collection do
			get 'uploadExe'
			post 'uploadExe'
		end
	end

  resources :variables

  resources :incidents do
		resources :micro_incidents
	end

	root to: "incidents#index"

end

app/models/incident.rb
class Incident < ActiveRecord::Base
	has_many :micro_incidents
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render action: 'show', status: :created, location: @incident }
      else
        format.html { render action: 'new' }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:incident_internal_ip, :incident_translated_ip, :incident_host_name, :incident_incident_time, :incident_detection_time, :incident_remediation_time, :incident_notes, :incident_remediation_actions, :incident_cert_tracking_number, :incident_permission_level, :incident_operating_system, :incident_location, :incident_exploited_application, :incident_cause, :incident_exploit_cve, :incident_incident_category, :incident_incidnet_name, :external_attackers_ip, :external_attackers_country, :external_attack_tool, :external_impact_to_server)
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<strong>Incidnet name:</strong><br>
		<%= f.text_field :incident_incidnet_name %>
	</div>
	<div class="field">
		<strong>Internal IP:</strong><br>
		<%= f.text_field :incident_internal_ip %>
	</div>
	<div class="field">
		<strong>Translated IP:</strong><br>
		<%= f.text_field :incident_translated_ip %>
	</div>
	<div class="field">
		<strong>Host name:</strong><br>
		<%= f.text_field :incident_host_name %>
	</div>
	<div class="field">
		<strong>Incident category:</strong><br>
		<%= f.text_field :incident_incident_category %>
	</div>
	<div class="field">
		<strong>Time of incident:</strong><br>
		<%= f.datetime_select :incident_incident_time %>
	</div>
	<div class="field">
		<strong>Time incident was detected:</strong><br>
		<%= f.datetime_select :incident_detection_time %>
	</div>
	<div class="field">
		<strong>Time of remediation:</strong><br>
		<%= f.datetime_select :incident_remediation_time %>
	</div>
	<div class="field">
		<strong>Notes:</strong><br>
		<%= f.text_area :incident_notes %>
	</div>
	<div class="field">
		<strong>Remediation actions:</strong><br>
		<%= f.text_area :incident_remediation_actions %>
	</div>
	<div class="field">
		<strong>CERT tracking ID:</strong><br>
		<%= f.text_field :incident_cert_tracking_number %>
	</div>
	<div class="field">
		<strong>Permission of user/application:</strong><br>
		<%= f.text_field :incident_permission_level %>
	</div>
	<div class="field">
		<strong>Affected OS:</strong><br>
		<%= f.text_field :incident_operating_system %>
	</div>
	<div class="field">
		<strong>Location of incident:</strong><br>
		<%= f.text_field :incident_location %>
	</div>
	<div class="field">
		<strong>Exploited application:</strong><br>
		<%= f.text_field :incident_exploited_application %>
	</div>
	<div class="field">
		<strong>Cause of incident:</strong><br>
		<%= f.text_field :incident_cause %>
	</div>
	<div class="field">
		<strong>Associated CVE:</strong><br>
		<%= f.text_field :incident_exploit_cve %>
	</div>
<h1>External Incident Info:</h1>
	<div class="field">
		<strong>Attackers IP:</strong><br>
		<%= f.text_field :external_attackers_ip %>
	</div>
	<div class="field">
		<strong>Attacers geolocation</strong><br>
		<%= f.text_field :external_attackers_country %>
	</div>
	<div class="field">
		<strong>Attack tool:</strong><br>
		<%= f.text_field :external_attack_tool %>
	</div>
	<div class="field">
		<strong>Impact on server:</strong><br>
		<%= f.text_field :external_impact_to_server %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/incidents/edit.html.erb
<center><h1>Editing incident</h1></center>

<div class=editincident>
	<%= render 'form' %>
</div>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<center><h1>Listing incidents</h1></center>
<center>
	<div class=centerbox>
		<table>
			<thead>
				<tr>

					<th>Incidnet name</th>
					<th>Category</th>
					<th>Location</th>
					<th>Time of incident</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<% @incidents.each do |incident| %>
					<tr>
						<td><center><%= incident.incident_incidnet_name %></center></td>
						<td><center><%= incident.incident_incident_category %></center></td>
						<td><center><%= incident.incident_location %></center></td>
						<td><center><%= incident.incident_incident_time %></center></td>
						<td><%= link_to 'Show', incident %></td>
						<td><%= link_to 'Edit', edit_incident_path(incident) %></td>
						<td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<%= link_to 'New Incident', new_incident_path %>
		<br>
	</div>
</center>

app/views/incidents/new.html.erb
<h1>New incident</h1>

<%= render 'form' %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Incident ID: <%=@incident.id%></h1></center><br />

<div class=showincident>
	<p>
		<strong>Incident name:</strong>
		<%= @incident.incident_incidnet_name %>
	</p>

	<p>
		<strong>Internal ip:</strong>
		<%= @incident.incident_internal_ip %>
	</p>

	<p>
		<strong>Translated IP:</strong>
		<%= @incident.incident_translated_ip %>
	</p>

	<p>
		<strong>Host name:</strong>
		<%= @incident.incident_host_name %>
	</p>

	<p>
		<strong>Incident category:</strong>
		<%= @incident.incident_incident_category %>
	</p>

	<p>
		<strong>Time of incident:</strong>
		<%= @incident.incident_incident_time %>
	</p>

	<p>
		<strong>Time incident was detected:</strong>
		<%= @incident.incident_detection_time %>
	</p>

	<p>
		<strong>Time of remediation:</strong>
		<%= @incident.incident_remediation_time %>
	</p>

	<p>
		<strong>Notes:</strong>
		<%= @incident.incident_notes %>
	</p>

	<p>
		<strong>Remediation actions:</strong>
		<%= @incident.incident_remediation_actions %>
	</p>

	<p>
		<strong>CERT tracking ID:</strong>
		<%= @incident.incident_cert_tracking_number %>
	</p>

	<p>
		<strong>Permission of user/application:</strong>
		<%= @incident.incident_permission_level %>
	</p>

	<p>
		<strong>Affected OS:</strong>
		<%= @incident.incident_operating_system %>
	</p>

	<p>
		<strong>Location of incident:</strong>
		<%= @incident.incident_location %>
	</p>

	<p>
		<strong>Exploited application:</strong>
		<%= @incident.incident_exploited_application %>
	</p>

	<p>
		<strong>Cause of incident:</strong>
		<%= @incident.incident_cause %>
	</p>

	<p>
		<strong>Associated CVE:</strong>
		<%= @incident.incident_exploit_cve %>
	</p>

	<p>
		<strong>Attackers IP:</strong>
		<%= @incident.external_attackers_ip %>
	</p>

	<p>
		<strong>Attackers geolocation:</strong>
		<%= @incident.external_attackers_country %>
	</p>

	<p>
		<strong>Attack tool:</strong>
		<%= @incident.external_attack_tool %>
	</p>

	<p>
		<strong>Impact to server:</strong>
		<%= @incident.external_impact_to_server %>
	</p>
	<%= link_to 'Edit', edit_incident_path(@incident) %> |
	<%= link_to 'Back', incidents_path %>
</div>