config/routes.rb
IncidentManagementFramework::Application.routes.draw do

  resources :executables do
		collection do
			get 'uploadExe'
			post 'uploadExe'
		end
	end

  resources :variables

  resources :incidents do
		resources :micro_incidents
	end

	root to: "incidents#index"

end

app/models/micro_incident.rb
class MicroIncident < ActiveRecord::Base
  belongs_to :incident
end

app/controllers/micro_incidents_controller.rb
class MicroIncidentsController < ApplicationController
  before_action :set_micro_incident, only: [:show, :edit, :update, :destroy]

  # GET /micro_incidents
  # GET /micro_incidents.json
  def index
    @micro_incidents = MicroIncident.all
  end

  # GET /micro_incidents/1
  # GET /micro_incidents/1.json
  def show
  end

  # GET /micro_incidents/new
  def new
    @micro_incident = MicroIncident.new
  end

  # GET /micro_incidents/1/edit
  def edit
  end

  # POST /micro_incidents
  # POST /micro_incidents.json
  def create
    @micro_incident = MicroIncident.new(micro_incident_params)

    respond_to do |format|
      if @micro_incident.save
        format.html { redirect_to @micro_incident, notice: 'Micro incident was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micro_incident }
      else
        format.html { render action: 'new' }
        format.json { render json: @micro_incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micro_incidents/1
  # PATCH/PUT /micro_incidents/1.json
  def update
    respond_to do |format|
      if @micro_incident.update(micro_incident_params)
        format.html { redirect_to @micro_incident, notice: 'Micro incident was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micro_incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micro_incidents/1
  # DELETE /micro_incidents/1.json
  def destroy
    @micro_incident.destroy
    respond_to do |format|
      format.html { redirect_to micro_incidents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micro_incident
      @micro_incident = MicroIncident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micro_incident_params
      params.require(:micro_incident).permit(:internal_malicious_ip, :internal_exploit_kit, :internal_malicious_url, :internal_malicious_resource, :internal_geographic_location, :internal_referrer_chian, :internal_mal_exe, :internal_mal_jar, :internal_mal_pdf, :internal_mal_xls, :internal_mal_doc, :internal_mal_eml, :incident_id)
    end
end

app/helpers/micro_incidents_helper.rb
module MicroIncidentsHelper
end

app/views/micro_incidents/_form.html.erb
<%= form_for(@micro_incident) do |f| %>
  <% if @micro_incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micro_incident.errors.count, "error") %> prohibited this micro_incident from being saved:</h2>

      <ul>
      <% @micro_incident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :internal_malicious_ip %><br>
    <%= f.text_field :internal_malicious_ip %>
  </div>
  <div class="field">
    <%= f.label :internal_exploit_kit %><br>
    <%= f.text_field :internal_exploit_kit %>
  </div>
  <div class="field">
    <%= f.label :internal_malicious_url %><br>
    <%= f.text_field :internal_malicious_url %>
  </div>
  <div class="field">
    <%= f.label :internal_malicious_resource %><br>
    <%= f.text_field :internal_malicious_resource %>
  </div>
  <div class="field">
    <%= f.label :internal_geographic_location %><br>
    <%= f.text_field :internal_geographic_location %>
  </div>
  <div class="field">
    <%= f.label :internal_referrer_chian %><br>
    <%= f.text_field :internal_referrer_chian %>
  </div>
  <div class="field">
    <%= f.label :internal_mal_exe %><br>
    <%= f.text_field :internal_mal_exe %>
  </div>
  <div class="field">
    <%= f.label :internal_mal_jar %><br>
    <%= f.text_field :internal_mal_jar %>
  </div>
  <div class="field">
    <%= f.label :internal_mal_pdf %><br>
    <%= f.text_field :internal_mal_pdf %>
  </div>
  <div class="field">
    <%= f.label :internal_mal_xls %><br>
    <%= f.text_field :internal_mal_xls %>
  </div>
  <div class="field">
    <%= f.label :internal_mal_doc %><br>
    <%= f.text_field :internal_mal_doc %>
  </div>
  <div class="field">
    <%= f.label :internal_mal_eml %><br>
    <%= f.text_field :internal_mal_eml %>
  </div>
  <div class="field">
    <%= f.label :incident_id %><br>
    <%= f.text_field :incident_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/micro_incidents/edit.html.erb
<h1>Editing micro_incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @micro_incident %> |
<%= link_to 'Back', micro_incidents_path %>

app/views/micro_incidents/index.html.erb
<h1>Listing micro_incidents</h1>

<table>
  <thead>
    <tr>
      <th>Internal malicious ip</th>
      <th>Internal exploit kit</th>
      <th>Internal malicious url</th>
      <th>Internal malicious resource</th>
      <th>Internal geographic location</th>
      <th>Internal referrer chian</th>
      <th>Internal mal exe</th>
      <th>Internal mal jar</th>
      <th>Internal mal pdf</th>
      <th>Internal mal xls</th>
      <th>Internal mal doc</th>
      <th>Internal mal eml</th>
      <th>Incident</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @micro_incidents.each do |micro_incident| %>
      <tr>
        <td><%= micro_incident.internal_malicious_ip %></td>
        <td><%= micro_incident.internal_exploit_kit %></td>
        <td><%= micro_incident.internal_malicious_url %></td>
        <td><%= micro_incident.internal_malicious_resource %></td>
        <td><%= micro_incident.internal_geographic_location %></td>
        <td><%= micro_incident.internal_referrer_chian %></td>
        <td><%= micro_incident.internal_mal_exe %></td>
        <td><%= micro_incident.internal_mal_jar %></td>
        <td><%= micro_incident.internal_mal_pdf %></td>
        <td><%= micro_incident.internal_mal_xls %></td>
        <td><%= micro_incident.internal_mal_doc %></td>
        <td><%= micro_incident.internal_mal_eml %></td>
        <td><%= micro_incident.incident %></td>
        <td><%= link_to 'Show', micro_incident %></td>
        <td><%= link_to 'Edit', edit_micro_incident_path(micro_incident) %></td>
        <td><%= link_to 'Destroy', micro_incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micro incident', new_micro_incident_path %>

app/views/micro_incidents/new.html.erb
<h1>New micro_incident</h1>

<%= render 'form' %>

<%= link_to 'Back', micro_incidents_path %>

app/views/micro_incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Internal malicious ip:</strong>
  <%= @micro_incident.internal_malicious_ip %>
</p>

<p>
  <strong>Internal exploit kit:</strong>
  <%= @micro_incident.internal_exploit_kit %>
</p>

<p>
  <strong>Internal malicious url:</strong>
  <%= @micro_incident.internal_malicious_url %>
</p>

<p>
  <strong>Internal malicious resource:</strong>
  <%= @micro_incident.internal_malicious_resource %>
</p>

<p>
  <strong>Internal geographic location:</strong>
  <%= @micro_incident.internal_geographic_location %>
</p>

<p>
  <strong>Internal referrer chian:</strong>
  <%= @micro_incident.internal_referrer_chian %>
</p>

<p>
  <strong>Internal mal exe:</strong>
  <%= @micro_incident.internal_mal_exe %>
</p>

<p>
  <strong>Internal mal jar:</strong>
  <%= @micro_incident.internal_mal_jar %>
</p>

<p>
  <strong>Internal mal pdf:</strong>
  <%= @micro_incident.internal_mal_pdf %>
</p>

<p>
  <strong>Internal mal xls:</strong>
  <%= @micro_incident.internal_mal_xls %>
</p>

<p>
  <strong>Internal mal doc:</strong>
  <%= @micro_incident.internal_mal_doc %>
</p>

<p>
  <strong>Internal mal eml:</strong>
  <%= @micro_incident.internal_mal_eml %>
</p>

<p>
  <strong>Incident:</strong>
  <%= @micro_incident.incident %>
</p>

<%= link_to 'Edit', edit_micro_incident_path(@micro_incident) %> |
<%= link_to 'Back', micro_incidents_path %>