config/routes.rb
IncidentManagementFramework::Application.routes.draw do

  resources :executables do
		collection do
			get 'uploadExe'
			post 'uploadExe'
		end
	end

  resources :variables

  resources :incidents do
		resources :micro_incidents
	end

	root to: "incidents#index"

end

app/models/variable.rb
class Variable < ActiveRecord::Base
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :set_variable, only: [:show, :edit, :update, :destroy]

  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
  end

  # GET /variables/new
  def new
    @variable = Variable.new
  end

  # GET /variables/1/edit
  def edit
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(variable_params)

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable was successfully created.' }
        format.json { render action: 'show', status: :created, location: @variable }
      else
        format.html { render action: 'new' }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variables/1
  # PATCH/PUT /variables/1.json
  def update
    respond_to do |format|
      if @variable.update(variable_params)
        format.html { redirect_to @variable, notice: 'Variable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to variables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variable
      @variable = Variable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variable_params
      params.require(:variable).permit(:location_options, :exploited_application_options, :social_engineering_options, :user_permissions_options, :operating_system_options, :incident_cause_options, :external_impact, :incident_category_options)
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= form_for(@variable) do |f| %>
  <% if @variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variable.errors.count, "error") %> prohibited this variable from being saved:</h2>

      <ul>
      <% @variable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_options %><br>
    <%= f.text_area :location_options %>
  </div>
  <div class="field">
    <%= f.label :exploited_application_options %><br>
    <%= f.text_area :exploited_application_options %>
  </div>
  <div class="field">
    <%= f.label :social_engineering_options %><br>
    <%= f.text_area :social_engineering_options %>
  </div>
  <div class="field">
    <%= f.label :user_permissions_options %><br>
    <%= f.text_area :user_permissions_options %>
  </div>
  <div class="field">
    <%= f.label :operating_system_options %><br>
    <%= f.text_area :operating_system_options %>
  </div>
  <div class="field">
    <%= f.label :incident_cause_options %><br>
    <%= f.text_area :incident_cause_options %>
  </div>
  <div class="field">
    <%= f.label :external_impact %><br>
    <%= f.text_area :external_impact %>
  </div>
  <div class="field">
    <%= f.label :incident_category_options %><br>
    <%= f.text_area :incident_category_options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variables/edit.html.erb
<h1>Editing variable</h1>

<%= render 'form' %>

<%= link_to 'Show', @variable %> |
<%= link_to 'Back', variables_path %>

app/views/variables/index.html.erb
<h1>Listing variables</h1>

<table>
  <thead>
    <tr>
      <th>Location options</th>
      <th>Exploited application options</th>
      <th>Social engineering options</th>
      <th>User permissions options</th>
      <th>Operating system options</th>
      <th>Incident cause options</th>
      <th>External impact</th>
      <th>Incident category options</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @variables.each do |variable| %>
      <tr>
        <td><%= variable.location_options %></td>
        <td><%= variable.exploited_application_options %></td>
        <td><%= variable.social_engineering_options %></td>
        <td><%= variable.user_permissions_options %></td>
        <td><%= variable.operating_system_options %></td>
        <td><%= variable.incident_cause_options %></td>
        <td><%= variable.external_impact %></td>
        <td><%= variable.incident_category_options %></td>
        <td><%= link_to 'Show', variable %></td>
        <td><%= link_to 'Edit', edit_variable_path(variable) %></td>
        <td><%= link_to 'Destroy', variable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variable', new_variable_path %>

app/views/variables/new.html.erb
<h1>New variable</h1>

<%= render 'form' %>

<%= link_to 'Back', variables_path %>

app/views/variables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location options:</strong>
  <%= @variable.location_options %>
</p>

<p>
  <strong>Exploited application options:</strong>
  <%= @variable.exploited_application_options %>
</p>

<p>
  <strong>Social engineering options:</strong>
  <%= @variable.social_engineering_options %>
</p>

<p>
  <strong>User permissions options:</strong>
  <%= @variable.user_permissions_options %>
</p>

<p>
  <strong>Operating system options:</strong>
  <%= @variable.operating_system_options %>
</p>

<p>
  <strong>Incident cause options:</strong>
  <%= @variable.incident_cause_options %>
</p>

<p>
  <strong>External impact:</strong>
  <%= @variable.external_impact %>
</p>

<p>
  <strong>Incident category options:</strong>
  <%= @variable.incident_category_options %>
</p>

<%= link_to 'Edit', edit_variable_path(@variable) %> |
<%= link_to 'Back', variables_path %>